import React, { useState } from 'react';
import {
  BrainCircuit,
  ChevronDown,
  ChevronUp,
  Sparkles,
  CheckCircle2,
  TrendingUp,
  TrendingDown,
  Info,
} from 'lucide-react';

export default function AIExplanation({
  xaiFactors = [],
  severityScore = 94,
  priority = 'Critical',
  aiConfidence = 92,
}) {
  const [expandedIndex, setExpandedIndex] = useState(null);

  const toggleExpand = idx => {
    setExpandedIndex(prev => (prev === idx ? null : idx));
  };

  return (
    <div
      style={{
        backgroundColor: 'var(--color-surface)',
        border: '1px solid var(--color-ai-border)',
        borderRadius: 'var(--radius-md)',
        padding: '20px 24px',
        boxShadow: 'var(--shadow-xs)',
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
      }}
    >
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: '10px' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '4px' }}>
            <span
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '4px',
                padding: '2px 8px',
                borderRadius: '4px',
                backgroundColor: 'var(--color-ai-tint)',
                color: 'var(--color-ai)',
                fontSize: '0.6875rem',
                fontWeight: 800,
                letterSpacing: '0.04em',
              }}
            >
              <BrainCircuit size={12} /> CONCRETE EXPLAINABLE AI (XAI)
            </span>
          </div>
          <h3 style={{ fontSize: '1.05rem', fontWeight: 800, color: 'var(--color-ink)', margin: 0 }}>
            Why was this complaint marked {priority}?
          </h3>
          <p style={{ fontSize: '0.75rem', color: 'var(--color-ink-muted)', marginTop: '2px' }}>
            Factor attribution breakdown generated by multi-modal NLP & GIS inference models
          </p>
        </div>

        {/* Score Pill */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: '10px',
            padding: '6px 14px',
            backgroundColor: priority === 'Critical' ? 'var(--color-critical-bg)' : 'var(--color-primary-tint)',
            border: priority === 'Critical' ? '1px solid var(--color-critical-border)' : '1px solid var(--color-border)',
            borderRadius: 'var(--radius-sm)',
          }}
        >
          <div>
            <div style={{ fontSize: '0.6875rem', fontWeight: 600, color: 'var(--color-ink-muted)', textTransform: 'uppercase' }}>
              Final Severity
            </div>
            <div style={{ fontSize: '1rem', fontWeight: 800, color: priority === 'Critical' ? 'var(--color-critical)' : 'var(--color-primary)' }}>
              {severityScore} / 100
            </div>
          </div>
          <div style={{ width: '1px', height: '24px', backgroundColor: 'var(--color-border)' }} />
          <div>
            <div style={{ fontSize: '0.6875rem', fontWeight: 600, color: 'var(--color-ink-muted)', textTransform: 'uppercase' }}>
              Confidence
            </div>
            <div style={{ fontSize: '1rem', fontWeight: 800, color: 'var(--color-ai)' }}>
              {aiConfidence}%
            </div>
          </div>
        </div>
      </div>

      {/* Contributing Factors List */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
        <div style={{ fontSize: '0.72rem', fontWeight: 700, textTransform: 'uppercase', color: 'var(--color-ink-muted)', letterSpacing: '0.03em' }}>
          Key Contributing Factors ({xaiFactors.length})
        </div>

        {xaiFactors.length === 0 ? (
          <div style={{ padding: '16px', textAlign: 'center', color: 'var(--color-ink-muted)', fontSize: '0.75rem' }}>
            No specific XAI contributing factors recorded for this ticket.
          </div>
        ) : (
          xaiFactors.map((factor, index) => {
            const isExpanded = expandedIndex === index;
            const isPositive = factor.contribution >= 0;

            return (
              <div
                key={index}
                style={{
                  border: '1px solid var(--color-border)',
                  borderRadius: 'var(--radius-sm)',
                  backgroundColor: isExpanded ? '#FFFFFF' : 'var(--color-surface-sunken)',
                  overflow: 'hidden',
                  transition: 'all 0.1s ease',
                }}
              >
                <div
                  onClick={() => toggleExpand(index)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    padding: '10px 14px',
                    cursor: 'pointer',
                    userSelect: 'none',
                    gap: '12px',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flex: 1, minWidth: 0 }}>
                    <div
                      style={{
                        padding: '2px 8px',
                        borderRadius: 'var(--radius-xs)',
                        backgroundColor: isPositive ? 'var(--color-primary-tint)' : 'var(--color-critical-bg)',
                        color: isPositive ? 'var(--color-primary)' : 'var(--color-critical)',
                        border: isPositive ? '1px solid var(--color-border)' : '1px solid var(--color-critical-border)',
                        fontSize: '0.72rem',
                        fontWeight: 800,
                        fontFamily: 'var(--font-data)',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '2px',
                        flexShrink: 0,
                      }}
                    >
                      {isPositive ? <TrendingUp size={11} /> : <TrendingDown size={11} />}
                      {isPositive ? `+${factor.contribution}` : factor.contribution}
                    </div>

                    <span style={{ fontSize: '0.8125rem', fontWeight: 700, color: 'var(--color-ink)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                      {factor.name}
                    </span>
                  </div>

                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'var(--color-ink-muted)', flexShrink: 0 }}>
                    <span style={{ fontSize: '0.6875rem', fontWeight: 600 }}>
                      {isExpanded ? 'Hide' : 'Details'}
                    </span>
                    {isExpanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                  </div>
                </div>

                {isExpanded && (
                  <div
                    style={{
                      padding: '10px 14px 12px',
                      borderTop: '1px solid var(--color-border)',
                      backgroundColor: '#FFFFFF',
                      fontSize: '0.75rem',
                      color: 'var(--color-ink-muted)',
                      lineHeight: 1.45,
                    }}
                  >
                    <div style={{ fontWeight: 600, color: 'var(--color-ink)', marginBottom: '2px' }}>
                      Inference Rationale:
                    </div>
                    {factor.explanation}
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>

      {/* Bottom Transparency Badge */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '8px 12px',
          borderRadius: 'var(--radius-xs)',
          backgroundColor: 'var(--color-ai-tint)',
          border: '1px solid var(--color-ai-border)',
          fontSize: '0.6875rem',
          color: 'var(--color-ai)',
          fontWeight: 600,
        }}
      >
        <span>Model: Municipal Grievance Ensemble v2.6 (DistilBERT + GeoSpatial Clustering)</span>
        <span>Audit Verifiable</span>
      </div>
    </div>
  );
}
